ALTER TABLE imports ADD COLUMN IF NOT EXISTS archive_path TEXT;
ALTER TABLE imports ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ;
ALTER TABLE imports ADD COLUMN IF NOT EXISTS archive_status VARCHAR(20) DEFAULT 'PENDING';
