-- 05_advanced_alerts.sql
ALTER TABLE alert_rules 
ADD COLUMN IF NOT EXISTS scope_site_code VARCHAR(50),
ADD COLUMN IF NOT EXISTS frequency_count INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS frequency_window INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS schedule_start VARCHAR(5),
ADD COLUMN IF NOT EXISTS schedule_end VARCHAR(5),
ADD COLUMN IF NOT EXISTS email_notify BOOLEAN DEFAULT FALSE;
