"""Initial migration

Revision ID: 519fc267ffb9
Revises: 
Create Date: 2026-02-23 22:16:34.905451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '519fc267ffb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('condition_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('scope_site_code', sa.String(length=50), nullable=True),
    sa.Column('frequency_count', sa.Integer(), nullable=False),
    sa.Column('frequency_window', sa.Integer(), nullable=False),
    sa.Column('schedule_start', sa.String(length=5), nullable=True),
    sa.Column('schedule_end', sa.String(length=5), nullable=True),
    sa.Column('time_scope', sa.String(length=50), nullable=False),
    sa.Column('match_category', sa.String(length=50), nullable=True),
    sa.Column('match_keyword', sa.String(length=255), nullable=True),
    sa.Column('is_open_only', sa.Boolean(), nullable=False),
    sa.Column('sliding_window_days', sa.Integer(), nullable=False),
    sa.Column('sequence_enabled', sa.Boolean(), nullable=False),
    sa.Column('seq_a_category', sa.String(length=50), nullable=True),
    sa.Column('seq_a_keyword', sa.String(length=255), nullable=True),
    sa.Column('seq_b_category', sa.String(length=50), nullable=True),
    sa.Column('seq_b_keyword', sa.String(length=255), nullable=True),
    sa.Column('seq_max_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('seq_lookback_days', sa.Integer(), nullable=False),
    sa.Column('logic_enabled', sa.Boolean(), nullable=False),
    sa.Column('logic_tree', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('email_notify', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder', sa.String(length=100), nullable=False),
    sa.Column('last_uid', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_bookmarks_folder'), 'email_bookmarks', ['folder'], unique=True)
    op.create_table('event_code_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('alertable_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_code_catalog_code'), 'event_code_catalog', ['code'], unique=True)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_code', sa.String(length=50), nullable=False),
    sa.Column('incident_key', sa.String(length=128), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('open_event_id', sa.BigInteger(), nullable=True),
    sa.Column('close_event_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_code', 'incident_key', 'opened_at', name='uq_incident_unique')
    )
    op.create_index(op.f('ix_incidents_incident_key'), 'incidents', ['incident_key'], unique=False)
    op.create_index(op.f('ix_incidents_site_code'), 'incidents', ['site_code'], unique=False)
    op.create_table('ingestion_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('source_timezone', sa.String(length=50), nullable=False),
    sa.Column('provider_code', sa.String(length=50), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('detection', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parser_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extraction_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalization', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excel_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('csv_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_profiles_profile_id'), 'ingestion_profiles', ['profile_id'], unique=True)
    op.create_index(op.f('ix_ingestion_profiles_provider_code'), 'ingestion_profiles', ['provider_code'], unique=False)
    op.create_table('monitoring_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('ui_color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('recovery_email', sa.String(length=255), nullable=True),
    sa.Column('expected_emails_per_day', sa.Integer(), nullable=False),
    sa.Column('expected_frequency_type', sa.String(length=20), nullable=False),
    sa.Column('silence_threshold_minutes', sa.Integer(), nullable=False),
    sa.Column('monitoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_successful_import_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_attachment_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('email_match_keyword', sa.String(length=255), nullable=True),
    sa.Column('expected_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_providers_code'), 'monitoring_providers', ['code'], unique=True)
    op.create_table('replay_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('events_scanned', sa.Integer(), nullable=False),
    sa.Column('alerts_created', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_conditions_code'), 'rule_conditions', ['code'], unique=True)
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_client', sa.String(length=50), nullable=False),
    sa.Column('secondary_code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_info', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('config_override', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_code_client'), 'sites', ['code_client'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('profile_photo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=50), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_rule_hits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_rule_hit_unique', 'event_rule_hits', ['event_id', 'rule_id'], unique=True)
    op.create_index(op.f('ix_event_rule_hits_event_id'), 'event_rule_hits', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_rule_hits_rule_id'), 'event_rule_hits', ['rule_id'], unique=False)
    op.create_table('imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('events_count', sa.Integer(), nullable=False),
    sa.Column('duplicates_count', sa.Integer(), nullable=False),
    sa.Column('unmatched_count', sa.Integer(), nullable=False),
    sa.Column('adapter_name', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('import_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('archive_path', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_status', sa.String(length=20), nullable=False),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('source_message_id', sa.String(length=255), nullable=True),
    sa.Column('archived_pdf_hash', sa.String(length=64), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['monitoring_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imports_adapter_name'), 'imports', ['adapter_name'], unique=False)
    op.create_index(op.f('ix_imports_file_hash'), 'imports', ['file_hash'], unique=False)
    op.create_index(op.f('ix_imports_source_message_id'), 'imports', ['source_message_id'], unique=False)
    op.create_table('profile_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['ingestion_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('code_site', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_import_id', sa.Integer(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['monitoring_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_site_connection_unique', 'site_connections', ['provider_id', 'code_site'], unique=True)
    op.create_index(op.f('ix_site_connections_code_site'), 'site_connections', ['code_site'], unique=False)
    op.create_index(op.f('ix_site_connections_provider_id'), 'site_connections', ['provider_id'], unique=False)
    op.create_table('smtp_provider_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('match_value', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('expected_emails_per_day', sa.Integer(), nullable=True),
    sa.Column('expected_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['monitoring_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smtp_provider_rules_provider_id'), 'smtp_provider_rules', ['provider_id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('code_zone', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('site_code', sa.String(length=50), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('weekday_label', sa.String(length=20), nullable=True),
    sa.Column('raw_message', sa.Text(), nullable=True),
    sa.Column('normalized_message', sa.Text(), nullable=True),
    sa.Column('raw_code', sa.String(length=50), nullable=True),
    sa.Column('normalized_type', sa.String(length=100), nullable=True),
    sa.Column('sub_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('zone_label', sa.String(length=255), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('dup_count', sa.Integer(), nullable=False),
    sa.Column('in_maintenance', sa.Boolean(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('alertable_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    op.create_index(op.f('ix_events_normalized_message'), 'events', ['normalized_message'], unique=False)
    op.create_index(op.f('ix_events_normalized_type'), 'events', ['normalized_type'], unique=False)
    op.create_index(op.f('ix_events_site_code'), 'events', ['site_code'], unique=False)
    op.create_index('ix_events_site_severity_time', 'events', ['site_code', 'severity', 'time'], unique=False)
    op.create_index('ix_events_site_time', 'events', ['site_code', 'time'], unique=False)
    op.create_index('ix_events_site_type_time', 'events', ['site_code', 'normalized_type', 'time'], unique=False)
    op.create_index(op.f('ix_events_time'), 'events', ['time'], unique=False)
    op.create_table('reprocess_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('audit_log_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['audit_log_id'], ['audit_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reprocess_jobs')
    op.drop_index(op.f('ix_events_time'), table_name='events')
    op.drop_index('ix_events_site_type_time', table_name='events')
    op.drop_index('ix_events_site_time', table_name='events')
    op.drop_index('ix_events_site_severity_time', table_name='events')
    op.drop_index(op.f('ix_events_site_code'), table_name='events')
    op.drop_index(op.f('ix_events_normalized_type'), table_name='events')
    op.drop_index(op.f('ix_events_normalized_message'), table_name='events')
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.drop_table('events')
    op.drop_table('zones')
    op.drop_index(op.f('ix_smtp_provider_rules_provider_id'), table_name='smtp_provider_rules')
    op.drop_table('smtp_provider_rules')
    op.drop_index(op.f('ix_site_connections_provider_id'), table_name='site_connections')
    op.drop_index(op.f('ix_site_connections_code_site'), table_name='site_connections')
    op.drop_index('ix_site_connection_unique', table_name='site_connections')
    op.drop_table('site_connections')
    op.drop_table('profile_revisions')
    op.drop_index(op.f('ix_imports_source_message_id'), table_name='imports')
    op.drop_index(op.f('ix_imports_file_hash'), table_name='imports')
    op.drop_index(op.f('ix_imports_adapter_name'), table_name='imports')
    op.drop_table('imports')
    op.drop_index(op.f('ix_event_rule_hits_rule_id'), table_name='event_rule_hits')
    op.drop_index(op.f('ix_event_rule_hits_event_id'), table_name='event_rule_hits')
    op.drop_index('ix_event_rule_hit_unique', table_name='event_rule_hits')
    op.drop_table('event_rule_hits')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sites_code_client'), table_name='sites')
    op.drop_table('sites')
    op.drop_table('settings')
    op.drop_index(op.f('ix_rule_conditions_code'), table_name='rule_conditions')
    op.drop_table('rule_conditions')
    op.drop_table('replay_jobs')
    op.drop_index(op.f('ix_monitoring_providers_code'), table_name='monitoring_providers')
    op.drop_table('monitoring_providers')
    op.drop_index(op.f('ix_ingestion_profiles_provider_code'), table_name='ingestion_profiles')
    op.drop_index(op.f('ix_ingestion_profiles_profile_id'), table_name='ingestion_profiles')
    op.drop_table('ingestion_profiles')
    op.drop_index(op.f('ix_incidents_site_code'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_key'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_event_code_catalog_code'), table_name='event_code_catalog')
    op.drop_table('event_code_catalog')
    op.drop_index(op.f('ix_email_bookmarks_folder'), table_name='email_bookmarks')
    op.drop_table('email_bookmarks')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
