"""feat_providers

Revision ID: aae331d676b0
Revises: 519fc267ffb9
Create Date: 2026-03-17 06:57:21.033606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aae331d676b0'
down_revision: Union[str, None] = '519fc267ffb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['monitoring_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_id', name='uq_user_provider_unique')
    )
    op.create_index(op.f('ix_user_providers_provider_id'), 'user_providers', ['provider_id'], unique=False)
    op.create_index(op.f('ix_user_providers_user_id'), 'user_providers', ['user_id'], unique=False)
    op.drop_index('ix_event_rule_hits_created_at', table_name='event_rule_hits')
    op.drop_index('ix_incidents_status', table_name='incidents')
    op.add_column('ingestion_profiles', sa.Column('allowed_extensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[\"pdf\", \"xls\", \"xlsx\"]'::jsonb")))
    op.add_column('ingestion_profiles', sa.Column('required_text', sa.String(length=255), nullable=True))
    op.alter_column('ingestion_profiles', 'format_kind',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'XLSX_NATIVE'::character varying"))
    op.drop_index('idx_ingestion_profiles_lookup', table_name='ingestion_profiles')
    op.add_column('monitoring_providers', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('monitoring_providers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('monitoring_providers', sa.Column('email_from', sa.String(length=255), nullable=True))
    op.add_column('monitoring_providers', sa.Column('email_scan_interval', sa.Integer(), nullable=True))
    op.alter_column('monitoring_providers', 'pdf_warning_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.9'))
    op.alter_column('monitoring_providers', 'pdf_critical_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.7'))
    op.alter_column('monitoring_providers', 'pdf_ignore_case',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('monitoring_providers', 'pdf_ignore_accents',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('monitoring_providers', 'quality_min_created_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               comment=None,
               existing_comment='Minimum ratio (events_created / rows_detected) before triggering a WARN status.',
               existing_server_default=sa.text('0.8'))
    op.alter_column('monitoring_providers', 'quality_alert_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='Whether to calculate and display quality status for this provider.',
               existing_server_default=sa.text('true'))
    op.alter_column('monitoring_providers', 'max_emails_per_day',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monitoring_providers', 'max_emails_per_day',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('monitoring_providers', 'quality_alert_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='Whether to calculate and display quality status for this provider.',
               existing_server_default=sa.text('true'))
    op.alter_column('monitoring_providers', 'quality_min_created_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               comment='Minimum ratio (events_created / rows_detected) before triggering a WARN status.',
               existing_server_default=sa.text('0.8'))
    op.alter_column('monitoring_providers', 'pdf_ignore_accents',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('monitoring_providers', 'pdf_ignore_case',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('monitoring_providers', 'pdf_critical_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.7'))
    op.alter_column('monitoring_providers', 'pdf_warning_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.9'))
    op.drop_column('monitoring_providers', 'email_scan_interval')
    op.drop_column('monitoring_providers', 'email_from')
    op.drop_column('monitoring_providers', 'deleted_at')
    op.drop_column('monitoring_providers', 'is_archived')
    op.create_index('idx_ingestion_profiles_lookup', 'ingestion_profiles', ['provider_code', 'format_kind', 'is_active'], unique=False)
    op.alter_column('ingestion_profiles', 'format_kind',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'XLSX_NATIVE'::character varying"))
    op.drop_column('ingestion_profiles', 'required_text')
    op.drop_column('ingestion_profiles', 'allowed_extensions')
    op.create_index('ix_incidents_status', 'incidents', ['status'], unique=False)
    op.create_index('ix_event_rule_hits_created_at', 'event_rule_hits', ['created_at'], unique=False)
    op.drop_index(op.f('ix_user_providers_user_id'), table_name='user_providers')
    op.drop_index(op.f('ix_user_providers_provider_id'), table_name='user_providers')
    op.drop_table('user_providers')
    # ### end Alembic commands ###
